# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyCd', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisionCd', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('descs', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelCd', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionCd', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentCd', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('intervalType', models.CharField(choices=[('D', 'Day'), ('M', 'Month'), ('Y', 'Year')], max_length=1)),
                ('proRate', models.BooleanField(default=True)),
                ('proRateVal', models.IntegerField()),
                ('tax', models.BooleanField(default=True)),
                ('absentDeduct', models.BooleanField(default=True)),
                ('payrollDeduct', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollComponentDtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descs', models.CharField(max_length=150)),
                ('calcType', models.CharField(choices=[('A', 'Amount'), ('P', 'Percentage')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=21)),
                ('companyExpense', models.DecimalField(decimal_places=2, max_digits=21)),
                ('payrollComponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrollcomponentdtls', to='mainapp.PayrollComponent')),
            ],
        ),
    ]
