# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemeCd', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proRateCd', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('proRateVal', models.CharField(choices=[('W', 'Working Days'), ('C', 'Calendar Days')], max_length=1)),
                ('proRateValCus', models.IntegerField()),
                ('proRateDivider', models.CharField(choices=[('W', 'Working Days'), ('C', 'Calendar Days'), ('X', 'Custom')], max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='payrollcomponentdtl',
            old_name='amount',
            new_name='companyVal',
        ),
        migrations.RenameField(
            model_name='payrollcomponentdtl',
            old_name='companyExpense',
            new_name='employeeVAl',
        ),
        migrations.RemoveField(
            model_name='payrollcomponent',
            name='proRateVal',
        ),
        migrations.AddField(
            model_name='payrollcomponent',
            name='compSubsidize',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollcomponentdtl',
            name='maxSalaryCalc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payrollcomponent',
            name='proRate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProRate'),
        ),
        migrations.AlterField(
            model_name='payrollcomponentdtl',
            name='payrollComponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrollComponentDtls', to='mainapp.PayrollComponent'),
        ),
        migrations.AddField(
            model_name='payrollscheme',
            name='payrollComponents',
            field=models.ManyToManyField(to='mainapp.PayrollComponent'),
        ),
    ]
