# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='identityNo',
            field=models.CharField(default='-', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careerinfo',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careerInfos', to='mainapp.Personal'),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educationInfos', to='mainapp.Personal'),
        ),
        migrations.AlterField(
            model_name='familyinfo',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familyInfos', to='mainapp.Personal'),
        ),
        migrations.AlterUniqueTogether(
            name='personal',
            unique_together=set([('identityType', 'identityNo')]),
        ),
    ]
