# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180425_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Overtime'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='isOvertime',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
