# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180129_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prorate',
            old_name='proRateValCus',
            new_name='proRateDivCus',
        ),
    ]
