# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-30 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180427_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='timeOffScheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainapp.TimeOffScheme'),
            preserve_default=False,
        ),
    ]
