# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180201_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeOffCd', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('resetBy', models.CharField(choices=[('J', 'Join Date'), ('E', 'Expiry'), ('F', 'First Day Of Year'), ('C', 'Custom Date')], max_length=1)),
                ('customDate', models.DateField()),
                ('timeOffVal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeOffScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemeCd', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('timeOffPolicies', models.ManyToManyField(to='mainapp.TimeOffPolicy')),
            ],
        ),
    ]
