# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_employee_timeoffscheme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='qualificatioinCd',
            new_name='qualificationCd',
        ),
    ]
