# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_timeoffpolicy_timeoffscheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollcomponent',
            name='intervalType',
        ),
        migrations.AddField(
            model_name='payrollcomponent',
            name='calcType',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payrollcomponent',
            name='proRate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.ProRate'),
        ),
    ]
