# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180514_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinfo',
            name='qualification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Qualification'),
            preserve_default=False,
        ),
    ]
