# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180206_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtimeCd', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('roundingMin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OvertimeDtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'Weekday'), ('H', 'Weekend/Holiday')], max_length=1)),
                ('multplyFrom', models.DecimalField(decimal_places=1, max_digits=2)),
                ('multplyTo', models.DecimalField(decimal_places=1, max_digits=2)),
                ('multplyBy', models.DecimalField(decimal_places=1, max_digits=3)),
                ('overtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimeDtls', to='mainapp.Overtime')),
            ],
        ),
        migrations.CreateModel(
            name='TaxSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptkpPribadi', models.DecimalField(decimal_places=0, max_digits=12)),
                ('ptkpIstri', models.DecimalField(decimal_places=0, max_digits=12)),
                ('ptkpTanggungan', models.DecimalField(decimal_places=0, max_digits=12)),
                ('maxTanggungan', models.IntegerField()),
                ('rounding', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Company', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxSetupDtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaryBottom', models.DecimalField(decimal_places=0, max_digits=12)),
                ('salaryTop', models.DecimalField(decimal_places=0, max_digits=12)),
                ('taxNpwp', models.DecimalField(decimal_places=1, max_digits=3)),
                ('taxNonNpwp', models.DecimalField(decimal_places=1, max_digits=3)),
                ('taxSetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxSetupDtls', to='mainapp.TaxSetup')),
            ],
        ),
        migrations.RenameField(
            model_name='payrollscheme',
            old_name='payrollComponents',
            new_name='payrollComponent',
        ),
        migrations.RenameField(
            model_name='timeoffscheme',
            old_name='timeOffPolicies',
            new_name='timeOffPolicy',
        ),
    ]
