# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20180214_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtimedtl',
            old_name='multplyBy',
            new_name='multiplyBy',
        ),
        migrations.RenameField(
            model_name='overtimedtl',
            old_name='multplyFrom',
            new_name='multiplyFrom',
        ),
        migrations.RenameField(
            model_name='overtimedtl',
            old_name='multplyTo',
            new_name='multiplyTo',
        ),
    ]
