# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_educationinfo_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerinfo',
            name='periodEnd',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careerinfo',
            name='periodStart',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
