# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_absentpattern_absentpatterndtl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxsetup',
            name='id',
        ),
        migrations.AlterField(
            model_name='taxsetup',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.Company'),
        ),
    ]
