# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20180219_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absentpatterndtl',
            name='period',
        ),
        migrations.AddField(
            model_name='absentpatterndtl',
            name='dayPeriod',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tueday'), (3, 'Wednesday'), (4, 'Thrusday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
            preserve_default=False,
        ),
    ]
