# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20180219_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absentpatterndtl',
            name='status',
        ),
        migrations.AddField(
            model_name='absentpatterndtl',
            name='dayStatus',
            field=models.CharField(choices=[('I', 'In'), ('O', 'Off')], default='I', max_length=1),
            preserve_default=False,
        ),
    ]
